### ISSUE TITLE
Diff functionality broken by #43

### ISSUE THREAD

**Issue by chosak** [cfpb/eregs-2.0#51]
PR #43 removed the `DiffNode` model but didn't reimplement the diff viewing functionality in [`eregs_core.views.diff`](https://github.com/cfpb/eregs-2.0/blob/master/eregs_core/views.py#L145) (note references to `DiffNode` remain there).

This breaks the ability to view diffs on the website.

## Current behavior

Diffing functionality is broken due to references to removed model.

## Expected behavior

Diffing functionality works as expected.

## Steps to replicate behavior (include URLs)

1. Visit a diff URL (e.g. [this](http://localhost:8000/diff/2015-26607/2020-01-01/2013-31223/2014-01-01/1003-1) with Reg E data loaded) and observe `NameError` exception is raised.

**Comment by grapesmoker** [comment]
This should be fixed now.

**Comment by chosak** [comment]
Thanks for the fix!
